version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:7
    container_name: omni-chat-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: omni_chat
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - omni-chat-network

  # Redis for task queue and streaming
  redis:
    image: redis:7-alpine
    container_name: omni-chat-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - omni-chat-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: omni-chat-backend
    restart: unless-stopped
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/omni_chat?authSource=admin
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-this-in-production
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - GITHUB_MODELS_API_KEY=${GITHUB_MODELS_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    networks:
      - omni-chat-network
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Celery worker for AI task processing
  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: omni-chat-celery
    restart: unless-stopped
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/omni_chat?authSource=admin
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-this-in-production
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - GITHUB_MODELS_API_KEY=${GITHUB_MODELS_API_KEY}
    depends_on:
      - mongodb
      - redis
    networks:
      - omni-chat-network
    volumes:
      - ./backend:/app
    command: celery -A celery_app worker --loglevel=info --concurrency=4

  # Frontend React app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: omni-chat-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - omni-chat-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0

volumes:
  mongodb_data:
  redis_data:

networks:
  omni-chat-network:
    driver: bridge 